### ISSUE TITLE
Running syncdb fails

### ISSUE THREAD

**Issue by sycoso** [fsmi/odie-server#9]
When running ./manage.py syncdb on my local machine (arch), it fails with the following output:

    Operations to perform:                                
      Synchronize unmigrated apps: prfproto, fsmi, odie
      Apply all migrations: admin, contenttypes, auth, sessions
    Synchronizing apps without migrations:
      Creating tables...
      Installing custom SQL...
      Installing indexes...
    Running migrations:
      No migrations to apply.
    Traceback (most recent call last):
      File "./manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
        return self.handle_noargs(**options)
      File "/usr/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 36, in handle_noargs
        if not UserModel._default_manager.exists() and options.get('interactive'):
      File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 606, in exists
        return self.query.has_results(using=self.db)
      File "/usr/lib/python2.7/site-packages/django/db/models/sql/query.py", line 457, in has_results
        return compiler.has_results()
      File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 757, in has_results
        return bool(self.execute_sql(SINGLE))
      File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
        cursor.execute(sql, params)
      File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
      File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
        return self.cursor.execute(sql, params)
    django.db.utils.ProgrammingError: relation "auth_user" does not exist
    LINE 1: SELECT (1) AS "a" FROM "auth_user" LIMIT 1

**Comment by Kha** [comment]
Yeah, local DB setup has been broken since we've integrated the fsmi databases; odie-server development pretty much only happens on www-test (in contrast to odie-client). We'll ditch django for flask in the near future anyway, but if there's interest in odie-server development from non-webmasters, I'll try to include some working sample data in the next iteration.

**Comment by sycoso** [comment]
Oh, I see. That would be cool :)
